package:
    name: eman2
    version: 2.31

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    build:
        - cmake 3.14.*
        - {{ cdt('mesa-libgl-devel') }}      # [linux]

    host:
        - python 2.7.14
        - boost 1.66.*
        - libglu      # [linux]
