package:
    name: eman2
    version: 2.31

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    build:
        - cmake     3.14.*
        - {{ compiler('cxx') }}           # [not win]
        - {{ cdt('mesa-libgl-devel') }}   # [linux]

    host:
        - boost     1.66.*
        - eman-deps-cxx   18.0.*
        - libglu                          # [linux]
    
test:
  requires:
    - eman-deps     18.0.*
    - boost         1.66.*
  
  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh             # [not win]
    - call tests\run_tests.bat            # [win]
