package:
    name: eman2
    version: 2.31

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    build:
        - cmake 3.14.*
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux]

    host:
        - msinttypes  # [win]
        - boost 1.66.*
        - pydusa 1.15   openmpi{{ openmpi }}_12  # [not win]
        - fftw   3.3.8  nompi_*                  # [win]
        - numpy 1.13.*
        - ftgl
        - freetype 2.8.*  # [osx]
        - freetype 2.7.*  # [not osx]
        - gsl 2.4.*
        - hdf5 1.8.18
        - jpeg 9b
        - libtiff 4.0.9             # [not win]
        - libtiff 4.0.9 hafacce9_0  # [win]
        - libpng 1.6.34
        - zlib
        - libglu      # [linux]
    
test:
  requires:
    - eman-deps=16.0.*   openmpi{{ openmpi }}_1   # [not win]
    - eman-deps=16.0.*   1                        # [win]
    - boost 1.66.*
  
  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
