package:
    name: eman2
    version: 2.31

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    build:
        - cmake 3.14.*
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux]

    host:
        - eman-deps=16.0.*   openmpi{{ openmpi }}_1   # [not win]
        - eman-deps=16.0.*   1                        # [win]
        - boost 1.66.*
        - libglu      # [linux]
    
test:
  requires:
    - eman-deps=16.0.*   openmpi{{ openmpi }}_1   # [not win]
    - eman-deps=16.0.*   1                        # [win]
    - boost 1.66.*
  
  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
