version: 2

jobs:
  setup_cache:
    docker:
      - image: circleci/buildpack-deps:16.04
    environment:
      CMAKE_VERSION: 3.9
      BOOST_VERSION: 1.64
    steps:
      - run: sudo apt-get update && sudo apt-get install freeglut3-dev
      - checkout
      - run: source ci_support/setup_conda.sh
      - save_cache:
          key: mini-eman-deps-14.2-0
          paths:
            - ~/miniconda2

workflows:
  version: 2
  setup_cache:
    jobs:
      - setup_cache
