version: 2

jobs:
  build_no_recipe:
    docker:
      - image: cryoem/eman-deps:dev-18-circleci18
    steps:
      - checkout
      - run: bash ci_support/build_no_recipe.sh

  build_recipe:
    docker:
      - image: cryoem/eman-deps:dev-18-circleci18
    steps:
      - checkout
      - run: bash ci_support/build_recipe.sh

workflows:
  version: 2
  build_recipe_and_no_recipe:
    jobs:
      - build_no_recipe
      - build_recipe
